-- MySQL Script generated by MySQL Workbench
-- Wed May 14 14:28:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation_game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_generation_game_online` ;

-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_classe` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `poder` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_personagem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `especie` VARCHAR(255) NOT NULL,
  `nivel` VARCHAR(255) NOT NULL,
  `ferramenta` VARCHAR(255) NULL,
  `pontos_de_vida` VARCHAR(255) NOT NULL,
  `pontos_de_mana` VARCHAR(255) NULL,
  `tb_classe_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_personagem_tb_classe_idx` (`tb_classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_personagem_tb_classe`
    FOREIGN KEY (`tb_classe_id`)
    REFERENCES `db_generation_game_online`.`tb_classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `db_generation_game_online`.`tb_classe` (poder) VALUES
('Guerreiro'),
('Mago'),
('Arqueiro'),
('Assassino'),
('Curandeiro');

INSERT INTO `db_generation_game_online`.`tb_personagem` 
(nome, especie, nivel, ferramenta, pontos_de_vida, pontos_de_mana, tb_classe_id) 
VALUES
('Thorgal', 'Orc', 12, 'Machado de Batalha', 300, NULL, 1),
('Elaria', 'Elfa', 20, 'Cajado Arcano', 180, 250, 2),
('Kael', 'Humano', 15, 'Arco Longo', 220, 60, 3),
('Nyx', 'Sombrio', 18, 'Adagas Duplas', 160, 80, 4),
('Liora', 'Anjo', 22, 'Cetro da Luz', 200, 300, 5),
('Bram', 'Anão', 14, 'Martelo de Guerra', 280, NULL, 1),
('Zyra', 'Elfa Negra', 17, 'Punhal Envenenado', 150, 90, 4),
('Orion', 'Humano', 19, 'Arco Reforçado', 210, 50, 3);

SELECT * FROM tb_personagem WHERE pontos_de_vida < 200;
SELECT * FROM tb_personagem WHERE pontos_de_mana > 150;

SELECT * FROM tb_personagem WHERE nome LIKE '%a';

SELECT
  p.id,
  p.nome,
  p.especie,
  p.nivel,
  p.ferramenta,
  p.pontos_de_vida,
  p.pontos_de_mana,
  c.poder AS classe
FROM 
	tb_personagem p
INNER JOIN 
	tb_classe c ON p.tb_classe_id = c.id
ORDER BY 
	c.poder ASC;



